fix problem with empty runtime dependencies
This fixes the error
```
Error: A default port name could not be supplied.
Error: Unable to open port: Could not find Portfile in /Users/hmeine/System/macports_deptree
```
which is caused by `port deps libgcc-devel` outputting
```
Full Name: libgcc-devel @12-20220327_0+enable_stdlib_flag
Build Dependencies:   texinfo, cctools, gmp, isl, ld64, libiconv, libmpc, mpfr, zstd
Library Dependencies: zlib
Runtime Dependencies:
```
and port_deptree.py interpreting the last line as a single dependency with an empty name.
(`port deps` without further arguments then leads to the above message, because `port`
thinks it should look in the current directory for a `Portfile`.)